services:
  db:
    container_name: postgres
    build: 
      context: .
      dockerfile: docker/Dockerfile-pg
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=mysecretpassword
  keycloak:  
    container_name: keycloak
    build: 
      context: .
      dockerfile: docker/Dockerfile-keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=localhost
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_DATABASE=mydatabase
      - KC_DB_SCHEMA=keycloak
      # in PROD these should not be used!!
      - KC_HTTP_ENABLED=true 
      - KC_HOSTNAME_STRICT_HTTPS=false
    depends_on:
      - postgres
    command: ["start", "--db-username", "keycloak", "--db-password", "mysecretpassword"]
  webapp1:
    container_name: webapp1
    build: 
      context: .
      dockerfile: docker/Dockerfile-webapp
    ports:
      - "8000:8000"
      - "8443:8443"
    environment:
      - KEYCLOAK_URL=http://keycloak:8080
      - APP_NAME=myapp_1
      - APP_SECRET=my-app1-secret
      - REALM=longshot
      - PORT=8000
    depends_on:
      - keycloak
  webapp2:
    container_name: webapp2
    build: 
      context: .
      dockerfile: docker/Dockerfile-webapp
    ports:
      - "9000:9000"
    environment:
      - KEYCLOAK_URL=http://keycloak:8080
      - APP_NAME=myapp_2
      - APP_SECRET=my-app2-secret
      - REALM=longshot
      - PORT=9000
    depends_on:
      - keycloak
  # api:
  #   container_name: api
  #   build: 
  #     context: .
  #     dockerfile: docker/Dockerfile-api
  #   ports:
  #     - "9999:9999"
  #   environment:
  #     - KEYCLOAK_URL=http://keycloak:8080
  #     - APP_NAME=myapp_3
  #     - APP_SECRET=my-app3-secret
  #     - REALM=longshot
  #     - PORT=9999
  #   depends_on:
  #     - keycloak
