services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:18.0.0
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: ["start-dev"]
  webapp1:
    container_name: webapp1
    build: 
      context: ./webapp
    ports:
      - "8000:8000"
    environment:
      - KEYCLOAK_URL=http://keycloak:8080
      - APP_NAME=myapp_1
      - APP_SECRET=my-app1-secret
      - REALM=longshot
      - PORT=8000
    depends_on:
      - keycloak
  webapp2:
    container_name: webapp2
    build: 
      context: ./webapp
    ports:
      - "9000:9000"
    environment:
      - KEYCLOAK_URL=http://keycloak:8080
      - APP_NAME=myapp_2
      - APP_SECRET=my-app2-secret
      - REALM=longshot
      - PORT=9000
    depends_on:
      - keycloak
